[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/bose"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/bose/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/bose/callback"
  to = "/callback.html"
  status = 200